POST http://localhost:9000/todos/create
Content-Type: application/json

{
  "text": "Something todo",
  "description": "Some Description"
}

###
GET http://localhost:9000/todos HTTP/1.1

###

GET http://localhost:9000/todos/complete?id=3 HTTP/1.1